# Preprocessing Technique: Encoding Categorical Variables
**Member:** [Wijayasinghe RPBA / IT25102653]
**Technique:** Encoding Categorical Variables
**Dataset:** Tourism Recommendation Dataset

In [20]:
import pandas as pd
import matplotlib.pyplot as plt

 
df = pd.read_csv("output_after_outlier_removal.csv")

 
cat_cols = ["attraction_category", "attraction_level", "province"]
cardinality = df[cat_cols].nunique().sort_values()
cardinality

attraction_level        3
province               22
attraction_category    26
dtype: int64

### Prerequisite: cleaning a category label before encoding

In [21]:
 
print("season column not present at this stage - already removed by Feature Selection")

season column not present at this stage - already removed by Feature Selection

In [3]:
# Step 1: Label Encoding — for a genuinely ORDINAL column

df_encoded = df.copy()

level_order = {"3A": 0, "4A": 1, "5A": 2}
df_encoded["attraction_level_encoded"] = df_encoded["attraction_level"].map(level_order)
df_encoded = df_encoded.drop(columns=["attraction_level"])
df_encoded[["attraction_level_encoded"]].drop_duplicates().sort_values("attraction_level_encoded")

    attraction_level_encoded
87                         0
0                          1
2                          2

In [4]:
# Step 2: One-Hot Encoding — for NOMINAL (unordered) low/medium-cardinality columns

df_encoded = pd.get_dummies(df_encoded, columns=["attraction_category"], drop_first=True)
print("Shape after one-hot encoding attraction_category:", df_encoded.shape)

Shape after one-hot encoding attraction_category: (100000, 30)

In [5]:
sat_numeric = df["satisfaction_level"].map({"Neutral": 0, "Satisfied": 1, "Very Satisfied": 2})

province_target_means = sat_numeric.groupby(df["province"]).mean()
df_encoded["province_target_enc"] = df["province"].map(province_target_means)

print(province_target_means.sort_values(ascending=False).head())
df_encoded[["province_target_enc"]].drop_duplicates().head()

province
Zhejiang     1.659115
Guangdong    1.580707
Jiangsu      1.577940
Hunan        1.535797
Hubei        1.531401
Name: satisfaction_level, dtype: float64

   province_target_enc
0             1.427281
1             1.482789
2             1.577940
3             1.379714
4             1.519129

In [6]:
# Step 3: Target Encoding — for HIGH-cardinality columns

df_encoded = df_encoded.drop(columns=["province"])
print("Final shape after full encoding:", df_encoded.shape)

Final shape after full encoding: (100000, 30)

**Leakage caution (as flagged in the lecture's risk column):** Target encoding uses the target variable directly, so on a real pipeline it should be computed only on the training fold (e.g. via cross-validation) to avoid leakage — doing it on the full dataset here is just for demonstration.

## Generating output
This notebook is **4th** in the run order. Save the fully encoded dataset for the next person (Scaling).

In [26]:
df_encoded.to_csv("output_after_encoding.csv", index=False)
print("Saved output_after_encoding.csv - shape:", df_encoded.shape)

Saved output_after_encoding.csv - shape: (100000, 30)